// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestEnvoys.dtmi_akri_samples_memmon__1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class MemoryStatsTelemetry : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""MemoryStatsTelemetry"",""namespace"":""TestEnvoys.dtmi_akri_samples_memmon__1"",""fields"":[{""name"":""memoryStats"",""type"":{""type"":""record"",""name"":""Object_MemoryStats"",""namespace"":""TestEnvoys.dtmi_akri_samples_memmon__1"",""fields"":[{""name"":""managedMemory"",""type"":[""null"",""double""]},{""name"":""workingSet"",""type"":[""null"",""double""]}]}}]}");
		private TestEnvoys.dtmi_akri_samples_memmon__1.Object_MemoryStats _memoryStats;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return MemoryStatsTelemetry._SCHEMA;
			}
		}
		public TestEnvoys.dtmi_akri_samples_memmon__1.Object_MemoryStats memoryStats
		{
			get
			{
				return this._memoryStats;
			}
			set
			{
				this._memoryStats = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.memoryStats;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.memoryStats = (TestEnvoys.dtmi_akri_samples_memmon__1.Object_MemoryStats)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
