// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestEnvoys.dtmi_akri_samples_memmon__1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class Object_MemoryStats : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Object_MemoryStats\",\"namespace\":\"TestEnvoys.dtmi_akri_sa" +
				"mples_memmon__1\",\"fields\":[{\"name\":\"managedMemory\",\"type\":[\"null\",\"double\"]},{\"n" +
				"ame\":\"workingSet\",\"type\":[\"null\",\"double\"]}]}");
		private System.Nullable<System.Double> _managedMemory;
		private System.Nullable<System.Double> _workingSet;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Object_MemoryStats._SCHEMA;
			}
		}
		public System.Nullable<System.Double> managedMemory
		{
			get
			{
				return this._managedMemory;
			}
			set
			{
				this._managedMemory = value;
			}
		}
		public System.Nullable<System.Double> workingSet
		{
			get
			{
				return this._workingSet;
			}
			set
			{
				this._workingSet = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.managedMemory;
			case 1: return this.workingSet;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.managedMemory = (System.Nullable<System.Double>)fieldValue; break;
			case 1: this.workingSet = (System.Nullable<System.Double>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
