/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */
#![allow(non_camel_case_types)]
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct IncrementResponsePayload {
    // The Command response argument.
    #[serde(rename = "CounterResponse")]
    pub counter_response: i32,
}
