/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */

#![allow(missing_docs)]
#![allow(unused_imports)]
#![allow(dead_code)]
#![allow(non_snake_case)]
#![allow(clippy::result_large_err)]
pub mod common_types;
pub mod dtmi_ms_adr_SchemaRegistry__1;
