// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package dtmi_ms_adr_SchemaRegistry__1

type GetRequestPayload struct {
	GetSchemaRequest Object_Get_Request `json:"getSchemaRequest"`
}
