// Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT.
package dtmi_ms_adr_SchemaRegistry__1

type Object_Get_Request struct {
	Name *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}
