/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */
#![allow(non_camel_case_types)]

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum Enum_Ms_Adr_SchemaRegistry_Format__1 {
    #[serde(rename = "Delta/1.0")]
    Delta1,
    #[serde(rename = "JsonSchema/draft-07")]
    JsonSchemaDraft07,
}
