/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */
#![allow(non_camel_case_types)]
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::enum_ms_adr_schema_registry_format__1::Enum_Ms_Adr_SchemaRegistry_Format__1;
use super::enum_ms_adr_schema_registry_schema_type__1::Enum_Ms_Adr_SchemaRegistry_SchemaType__1;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct Object_Ms_Adr_SchemaRegistry_Schema__1 {
    /// The 'description' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub description: Option<String>,

    /// The 'displayName' Field.
    #[serde(rename = "displayName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub display_name: Option<String>,

    /// The 'format' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub format: Option<Enum_Ms_Adr_SchemaRegistry_Format__1>,

    /// The 'hash' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub hash: Option<String>,

    /// The 'name' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub name: Option<String>,

    /// The 'namespace' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub namespace: Option<String>,

    /// The 'schemaContent' Field.
    #[serde(rename = "schemaContent")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub schema_content: Option<String>,

    /// The 'schemaType' Field.
    #[serde(rename = "schemaType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub schema_type: Option<Enum_Ms_Adr_SchemaRegistry_SchemaType__1>,

    /// The 'tags' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub tags: Option<HashMap<String, String>>,

    /// The 'version' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub version: Option<String>,
}
