// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package dtmi_com_example_Counter__1

type TelemetryCollection struct {
	CounterValue *int32 `json:"CounterValue,omitempty"`
}
