/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.Akri.dtmi_com_microsoft_deviceregistry_DiscoveredAssetResources__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.Akri;

    public class CreateDiscoveredAssetEndpointProfileResponsePayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command response argument.
        /// </summary>
        [JsonPropertyName("createDiscoveredAssetEndpointProfileResponse")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public Object_CreateDiscoveredAssetEndpointProfile_Response CreateDiscoveredAssetEndpointProfileResponse { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (CreateDiscoveredAssetEndpointProfileResponse is null)
            {
                throw new ArgumentNullException("createDiscoveredAssetEndpointProfileResponse field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (CreateDiscoveredAssetEndpointProfileResponse is null)
            {
                throw new ArgumentNullException("createDiscoveredAssetEndpointProfileResponse field cannot be null");
            }
        }
    }
}
