/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.Akri.dtmi_com_microsoft_deviceregistry_DiscoveredAssetResources__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.Akri;

    public class Object_CreateDiscoveredAssetEndpointProfile_Request
    {
        /// <summary>
        /// A unique identifier for a discovered asset.
        /// </summary>
        [JsonPropertyName("additionalConfiguration")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? AdditionalConfiguration { get; set; } = default;

        /// <summary>
        /// Name of the discovered asset endpoint profile. If not provided it will get generated by Akri.
        /// </summary>
        [JsonPropertyName("daepName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? DaepName { get; set; } = default;

        /// <summary>
        /// Defines the configuration for the connector type that is being used with the endpoint profile.
        /// </summary>
        [JsonPropertyName("endpointProfileType")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? EndpointProfileType { get; set; } = default;

        /// <summary>
        /// list of supported authentication methods
        /// </summary>
        [JsonPropertyName("supportedAuthenticationMethods")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Enum_CreateDiscoveredAssetEndpointProfile_Request_SupportedAuthenticationMethods_ElementSchema>? SupportedAuthenticationMethods { get; set; } = default;

        /// <summary>
        /// local valid URI specifying the network address/dns name of southbound service.
        /// </summary>
        [JsonPropertyName("targetAddress")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? TargetAddress { get; set; } = default;

    }
}
