// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package counter

type ReadCounterResponsePayload struct {

	// The Command response argument.
	CounterResponse int32 `json:"CounterResponse"`
}
