// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package counter

type TelemetryCollection struct {

	// The current value of the counter.
	CounterValue *int32 `json:"CounterValue,omitempty"`
}
