/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace TestEnvoys.Memmon
{
    using System;
    using System.Collections.Generic;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.Telemetry;
    using Azure.Iot.Operations.Protocol.Models;
    using TestEnvoys;

    public static partial class Memmon
    {
        /// <summary>
        /// Specializes the <c>TelemetryReceiver</c> class for type <c>MemoryStatsTelemetry</c>.
        /// </summary>
        public class MemoryStatsTelemetryReceiver : TelemetryReceiver<MemoryStatsTelemetry>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="MemoryStatsTelemetryReceiver"/> class.
            /// </summary>
            public MemoryStatsTelemetryReceiver(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, new AvroSerializer<MemoryStatsTelemetry, EmptyAvro>())
            {
                TopicTokenMap["modelId"] = "dtmi:akri:samples:memmon;1";
                TopicTokenMap["telemetryName"] = "memoryStats";
            }
        }
    }
}
