/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace TestEnvoys.Counter
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using TestEnvoys;

    public static partial class Counter
    {
        /// <summary>
        /// Specializes a <c>CommandExecutor</c> class for Command 'increment'.
        /// </summary>
        public class IncrementCommandExecutor : CommandExecutor<IncrementRequestPayload, IncrementResponsePayload>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="IncrementCommandExecutor"/> class.
            /// </summary>
            public IncrementCommandExecutor(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "increment", new Utf8JsonSerializer())
            {
                TopicTokenMap["modelId"] = "dtmi:com:example:Counter;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["executorId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "increment";
            }
        }
    }
}
