// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT.
package dtmi_akri_samples_oven__1

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type TelemetryCollectionSender struct {
	*protocol.TelemetrySender[TelemetryCollection]
}

func NewTelemetryCollectionSender(
	client protocol.MqttClient,
	topic string,
	opt ...protocol.TelemetrySenderOption,
) (*TelemetryCollectionSender, error) {
	var err error
	sender := &TelemetryCollectionSender{}

	var opts protocol.TelemetrySenderOptions
	opts.Apply(
		opt,
	)

	sender.TelemetrySender, err = protocol.NewTelemetrySender(
		client,
		protocol.JSON[TelemetryCollection]{},
		topic,
		&opts,
	)

	return sender, err
}

func (sender TelemetryCollectionSender) SendTelemetryCollection(
	ctx context.Context,
	telemetry TelemetryCollection,
	opt ...protocol.SendOption,
) error {
	return sender.Send(ctx, telemetry, opt...)
}
