// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT.
package schemaregistry

type GetRequestSchema struct {
	Name *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}
