// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package schemaregistry

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type GetCommandInvoker struct {
	*protocol.CommandInvoker[GetRequestPayload, GetResponsePayload]
}

func NewGetCommandInvoker(
	app *protocol.Application,
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*GetCommandInvoker, error) {
	var err error
	invoker := &GetCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName":     "get",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		app,
		client,
		protocol.JSON[GetRequestPayload]{},
		protocol.JSON[GetResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker GetCommandInvoker) Get(
	ctx context.Context,
	request GetRequestPayload,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[GetResponsePayload], error) {
	response, err := invoker.Invoke(
		ctx,
		request,
		opt...,
	)

	return response, err
}
