// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT.
package schemaregistry

type GetRequestPayload struct {
	GetSchemaRequest GetRequestSchema `json:"getSchemaRequest"`
}
