// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package schemaregistry

type GetRequestPayload struct {

	// The Command request argument.
	GetSchemaRequest GetRequestSchema `json:"getSchemaRequest"`
}
