// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT.
package schemaregistry

type GetRequestSchema struct {

	// The 'name' Field.
	Name *string `json:"name,omitempty"`

	// The 'version' Field.
	Version *string `json:"version,omitempty"`
}
