// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package schemaregistry

type PutRequestSchema struct {
	Description *string `json:"description,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Format *Format `json:"format,omitempty"`
	SchemaContent *string `json:"schemaContent,omitempty"`
	SchemaType *SchemaType `json:"schemaType,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
	Version *string `json:"version,omitempty"`
}
