// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT.
package schemaregistry

type PutRequestPayload struct {
	PutSchemaRequest PutRequestSchema `json:"putSchemaRequest"`
}
