// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT.
package schemaregistry

type PutResponsePayload struct {

	// The Command response argument.
	Schema Schema `json:"schema"`
}
