// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package dtmi_com_example_Counter__1

import (
	"context"

	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type IncrementCommandInvoker struct {
	*protocol.CommandInvoker[any, IncrementResponsePayload]
}

func NewIncrementCommandInvoker(
	client protocol.MqttClient,
	requestTopic string,
	opt ...protocol.CommandInvokerOption,
) (*IncrementCommandInvoker, error) {
	var err error
	invoker := &IncrementCommandInvoker{}

	var opts protocol.CommandInvokerOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName":     "increment",
		},
	)

	invoker.CommandInvoker, err = protocol.NewCommandInvoker(
		client,
		protocol.Empty{},
		protocol.JSON[IncrementResponsePayload]{},
		requestTopic,
		&opts,
	)

	return invoker, err
}

func (invoker IncrementCommandInvoker) Increment(
	ctx context.Context,
	executorId string,
	opt ...protocol.InvokeOption,
) (*protocol.CommandResponse[IncrementResponsePayload], error) {
	var opts protocol.InvokeOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"executorId": executorId,
		},
	)

	response, err := invoker.Invoke(
		ctx,
		nil,
		&opts,
	)

	return response, err
}
