// Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT.
package dtmi_com_example_Counter__1

type IncrementResponsePayload struct {
	CounterResponse int32 `json:"CounterResponse"`
}
