// Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT.
package dtmi_com_example_Counter__1

import (
	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type IncrementCommandExecutor struct {
	*protocol.CommandExecutor[any, IncrementCommandResponse]
}

func NewIncrementCommandExecutor(
	client protocol.Client,
	requestTopic string,
	handler protocol.CommandHandler[any, IncrementCommandResponse],
	opt ...protocol.CommandExecutorOption,
) (*IncrementCommandExecutor, error) {
	var err error
	executor := &IncrementCommandExecutor{}

	var opts protocol.CommandExecutorOptions
	opts.Apply(
		opt,
		protocol.WithTopicTokens{
			"commandName": "increment",
		},
		protocol.WithIdempotent(false),
	)

	executor.CommandExecutor, err = protocol.NewCommandExecutor(
		client,
		protocol.Empty{},
		protocol.JSON[IncrementCommandResponse]{},
		requestTopic,
		handler,
		&opts,
	)

	return executor, err
}
