// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FibResponseSchema.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TestEnvoys.Math {

  /// <summary>Holder for reflection information generated from FibResponseSchema.proto</summary>
  public static partial class FibResponseSchemaReflection {

    #region Descriptor
    /// <summary>File descriptor for FibResponseSchema.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FibResponseSchemaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdGaWJSZXNwb25zZVNjaGVtYS5wcm90bxIETWF0aBoWRmliTnVtYmVyc1Nj",
            "aGVtYS5wcm90byJ5ChFGaWJSZXNwb25zZVNjaGVtYRIvCgpmaWJOdW1iZXJz",
            "GAIgASgLMhYuTWF0aC5GaWJOdW1iZXJzU2NoZW1hSACIAQESFgoJZmliUmVz",
            "dWx0GAEgASgRSAGIAQFCDQoLX2ZpYk51bWJlcnNCDAoKX2ZpYlJlc3VsdEIa",
            "CgRNYXRoUAGqAg9UZXN0RW52b3lzLk1hdGhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TestEnvoys.Math.FibNumbersSchemaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TestEnvoys.Math.FibResponseSchema), global::TestEnvoys.Math.FibResponseSchema.Parser, new[]{ "FibNumbers", "FibResult" }, new[]{ "FibNumbers", "FibResult" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FibResponseSchema : pb::IMessage<FibResponseSchema>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FibResponseSchema> _parser = new pb::MessageParser<FibResponseSchema>(() => new FibResponseSchema());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FibResponseSchema> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TestEnvoys.Math.FibResponseSchemaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FibResponseSchema() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FibResponseSchema(FibResponseSchema other) : this() {
      _hasBits0 = other._hasBits0;
      fibNumbers_ = other.fibNumbers_ != null ? other.fibNumbers_.Clone() : null;
      fibResult_ = other.fibResult_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FibResponseSchema Clone() {
      return new FibResponseSchema(this);
    }

    /// <summary>Field number for the "fibNumbers" field.</summary>
    public const int FibNumbersFieldNumber = 2;
    private global::TestEnvoys.Math.FibNumbersSchema fibNumbers_;
    /// <summary>
    /// The 'fibNumbers' Field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TestEnvoys.Math.FibNumbersSchema FibNumbers {
      get { return fibNumbers_; }
      set {
        fibNumbers_ = value;
      }
    }

    /// <summary>Field number for the "fibResult" field.</summary>
    public const int FibResultFieldNumber = 1;
    private readonly static int FibResultDefaultValue = 0;

    private int fibResult_;
    /// <summary>
    /// The 'fibResult' Field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FibResult {
      get { if ((_hasBits0 & 1) != 0) { return fibResult_; } else { return FibResultDefaultValue; } }
      set {
        _hasBits0 |= 1;
        fibResult_ = value;
      }
    }
    /// <summary>Gets whether the "fibResult" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFibResult {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "fibResult" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFibResult() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FibResponseSchema);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FibResponseSchema other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FibNumbers, other.FibNumbers)) return false;
      if (FibResult != other.FibResult) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (fibNumbers_ != null) hash ^= FibNumbers.GetHashCode();
      if (HasFibResult) hash ^= FibResult.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasFibResult) {
        output.WriteRawTag(8);
        output.WriteSInt32(FibResult);
      }
      if (fibNumbers_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FibNumbers);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasFibResult) {
        output.WriteRawTag(8);
        output.WriteSInt32(FibResult);
      }
      if (fibNumbers_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FibNumbers);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (fibNumbers_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FibNumbers);
      }
      if (HasFibResult) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(FibResult);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FibResponseSchema other) {
      if (other == null) {
        return;
      }
      if (other.fibNumbers_ != null) {
        if (fibNumbers_ == null) {
          FibNumbers = new global::TestEnvoys.Math.FibNumbersSchema();
        }
        FibNumbers.MergeFrom(other.FibNumbers);
      }
      if (other.HasFibResult) {
        FibResult = other.FibResult;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FibResult = input.ReadSInt32();
            break;
          }
          case 18: {
            if (fibNumbers_ == null) {
              FibNumbers = new global::TestEnvoys.Math.FibNumbersSchema();
            }
            input.ReadMessage(FibNumbers);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FibResult = input.ReadSInt32();
            break;
          }
          case 18: {
            if (fibNumbers_ == null) {
              FibNumbers = new global::TestEnvoys.Math.FibNumbersSchema();
            }
            input.ReadMessage(FibNumbers);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
